name: automated-testing-integration
on:
  push:
    branches:
      - staging
      - master
      - feature/Jorge
  workflow_dispatch:

jobs:
  integration-e2e-tests:
    uses: bancodebogota/bbog-dig-do-testing-pipeline/.github/workflows/test_frontend_integration.yml@v5
    with:
      command-install: 'mvn clean install -DskipTests'
      command-execute: 'mvn clean verify -D"webdriver.driver=remote" -D"webdriver.remote.url=https://hub.browserstack.com/wd/hub" -P"sample-test"'
      files-to-export: >
        target/site/serenity/serenity-summary.html
      prefix-team: ‘ldf'
      use-aws-credentials: false
      debug: false
      environment: 'st'
      release-id-steward: ${{ inputs.release_id }}
      path-report-file: 'target/serenity-reports/cucumber_report.json'
      repository: 'bbog-ldf-automated-testing'
      name-file-report: results.csv
    secrets:
      DIG_READER_GITHUB_ACCESS_TOKEN: ${{ secrets.DIG_READER_GITHUB_ACCESS_TOKEN }}
      CLIENT_ID_XRAY: ${{ secrets.CLIENT_ID_XRAY }}
      CLIENT_SECRET_XRAY: ${{ secrets.CLIENT_SECRET_XRAY }}